In [3]:
import pandas as pd

In [4]:
df =  pd.read_csv('data_arriendos_bicicletas.csv')

In [5]:
df

,fecha_hora,estacion_anio,festivo,dia_laboral,clima,temperatura,sensacion_termica,humedad,velocidad_viento,usuarios_ocasionales,usuarios_registrados,total_arriendos
0,2011-11-14 07:00:00,invierno,NO,si,DESPEJADO,18.04,21.970,72.0,16.9979,11.0,311.0,322
1,2011-12-05 19:00:00,invierno,No,si,Neblina,18.86,22.725,77.0,0.0000,13.0,295.0,308
2,2011-12-02 21:00:00,invier,NO,Si,Parcialmente nublado,13.94,16.665,49.0,12.9980,9.0,102.0,111
3,2011-11-05 19:00:00,Invierno,N,Fin de semana,DESPEJADO,13.94,18.180,53.0,0.0000,45.0,159.0,204
4,2011-09-10 22:00:00,Otoño,no,N,Parcialmente nublado,26.24,29.545,78.0,0.0000,49.0,126.0,175
...,...,...,...,...,...,...,...,...,...,...,...,...
10906,2012-01-14 02:00:00,Prim,no,0,Soleado,6.56,8.335,47.0,11.0014,6.0,NaN,38
10907,2011-12-10 09:00:00,Inv,0,No,Soleado,-30.00,12.880,61.0,19.0012,15.0,134.0,149
10908,2011-12-18 16:00:00,Inv,no,Fin de semana,DESPEJADO,11.48,NaN,48.0,16.9979,27.0,NaN,234
10909,2011-02-19 07:00:00,Primavera,NO,0,Claro,15.58,19.695,17.0,35.0008,6.0,16.0,22
10910,2012-05-02 07:00:00,Ver,NO,si,Niebla,22.14,25.760,88.0,12.9980,14.0,344.0,358

In [7]:
df = df[['humedad', 'velocidad_viento']]
df

       humedad  velocidad_viento
0         72.0           16.9979
1         77.0            0.0000
2         49.0           12.9980
3         53.0            0.0000
4         78.0            0.0000
...        ...               ...
10906     47.0           11.0014
10907     61.0           19.0012
10908     48.0           16.9979
10909     17.0           35.0008
10910     88.0           12.9980

[10911 rows x 2 columns]

In [8]:
filas_con_nan = df[df.isna().any(axis=1)]
cantidad_borradas = len(filas_con_nan)

df = df.dropna()

print("Cantidad de filas borradas:", cantidad_borradas)
print("Filas que se borraron:\n", filas_con_nan)

df

Cantidad de filas borradas: 828
Filas que se borraron:
        humedad  velocidad_viento
31         NaN           16.9979
49        64.0               NaN
50         NaN            8.9981
84        87.0               NaN
105       38.0               NaN
...        ...               ...
10794      NaN            7.0015
10836      NaN            8.9981
10841      NaN           15.0013
10848      NaN            8.9981
10904      NaN           15.0013

[828 rows x 2 columns]

       humedad  velocidad_viento
0         72.0           16.9979
1         77.0            0.0000
2         49.0           12.9980
3         53.0            0.0000
4         78.0            0.0000
...        ...               ...
10906     47.0           11.0014
10907     61.0           19.0012
10908     48.0           16.9979
10909     17.0           35.0008
10910     88.0           12.9980

[10083 rows x 2 columns]

In [9]:
criterio_filtro = (df['humedad'] >= 0) & (df['humedad'] <= 100) & (df['velocidad_viento'] >= 0) & (df['velocidad_viento'] <= 250)

filas_eliminadas = df[~criterio_filtro].copy()
filas_eliminadas['Fila_Excel'] = filas_eliminadas.index + 2

df = df[criterio_filtro]

print("Cantidad de filas eliminadas por inconsistencia física:", len(filas_eliminadas))
print("Detalle de filas eliminadas:")
filas_eliminadas

Cantidad de filas eliminadas por inconsistencia física: 59
Detalle de filas eliminadas:

       humedad  velocidad_viento  Fila_Excel
212      120.0           15.0013         214
240      -10.0           12.9980         242
433      110.0           11.0014         435
503      120.0           12.9980         505
629      150.0            8.9981         631
728      -10.0            8.9981         730
741      -10.0           26.0027         743
760      110.0           19.0012         762
790      110.0           15.0013         792
1072     110.0           11.0014        1074
1231     -10.0           12.9980        1233
1263     150.0           15.0013        1265
1397     120.0           12.9980        1399
1468     150.0           11.0014        1470
1607     -10.0           11.0014        1609
2022     120.0           19.9995        2024
2434      -5.0           19.9995        2436
2569     150.0           16.9979        2571
2593     150.0           15.0013        2595
3011     110.0           22.0028        3013
3312     120.0           15.0013        3314
3450     120.0           30.0026        3452
3479      -5.0           15.0013        3481
3726     150.0            8.9981        3728
4132     110.0            0.0000        4134
4174     120.0            0.0000        4176
4229     150.0           27.9993        4231
4377     120.0           19.9995        4379
4579     -10.0            0.0000        4581
4809     150.0           19.0012        4811
4820     150.0            7.0015        4822
5050      -5.0           16.9979        5052
5262     150.0           15.0013        5264
5575     -10.0            8.9981        5577
5662     110.0            7.0015        5664
5824     110.0           12.9980        5826
5932      -5.0           27.9993        5934
5950     120.0           16.9979        5952
6070     110.0           12.9980        6072
6393     -10.0            6.0032        6395
6576     150.0           12.9980        6578
6699      -5.0            0.0000        6701
6820     150.0           39.0007        6822
7150     110.0           16.9979        7152
7187      -5.0           12.9980        7189
7409     110.0            6.0032        7411
7471     120.0            7.0015        7473
7668     -10.0           12.9980        7670
7711     -10.0           12.9980        7713
7820     110.0            8.9981        7822
8049      -5.0            0.0000        8051
8473     110.0           22.0028        8475
8717     150.0           19.9995        8719
8765     110.0           26.0027        8767
8791     150.0           15.0013        8793
8946     150.0            8.9981        8948
9125     120.0           19.0012        9127
10656    110.0           11.0014       10658
10879    -10.0           19.0012       10881

In [10]:
df.describe()

            humedad  velocidad_viento
count  10024.000000      10024.000000
mean      61.895950         12.786908
std       19.299073          8.141289
min        0.000000          0.000000
25%       47.000000          7.001500
50%       62.000000         12.998000
75%       77.000000         16.997900
max      100.000000         56.996900

In [11]:
df

       humedad  velocidad_viento
0         72.0           16.9979
1         77.0            0.0000
2         49.0           12.9980
3         53.0            0.0000
4         78.0            0.0000
...        ...               ...
10906     47.0           11.0014
10907     61.0           19.0012
10908     48.0           16.9979
10909     17.0           35.0008
10910     88.0           12.9980

[10024 rows x 2 columns]